mindvalley:
  accounts:
    api:      https://accounts.mindvalley.com/
    key:      dr6PkK1xOxwT2a70cZcDJFZjVefR1UHQxyFcJcB1
    secret:   YHfpOzqI6Lmcg4rXYQDdlrFR2nF0Bk4q6xaEc784
  chargebee:
    #define a shared secret for webhook security
    shared_secret: 'testchargebe3'
    #get from chargebee site
    SITE: "mindvalleytest-test"
    API_KEY: "test_BKgZWuZFIz5np9D8HBucukFIfsAv8OTAn"